# PCA model Benedikt

## Imports & Loading DataFrame

In [100]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer, KNNImputer

In [9]:
data = pd.read_csv("../raw_data/final_data.v3.csv", low_memory=False)
pd.set_option('display.max_columns', 72)
data.reset_index(inplace=True)

In [4]:
data #out: 2189 rows × 72 columns

,index,Unnamed: 0,Organization Name,IPO Status,Number of Founders,Company Type,CB Rank (Company),Operating Status,Industry Groups,Number of Employees,...,a_to_seed_ratio,b_to_a_ratio,c_to_b_ratio,d_to_c_ratio,e_to_d_ratio,pe_to_e_ratio,total_funding_usd,industry_multiples,company_valuation,last_funding_type
0,0,0,air up,Private,5.0,For Profit,"1,347",Active,"Commerce and Shopping, Food and Beverage, Other",251-500,...,0.0,0.000000,0.000000,0.0,0.0,0.0,67922929.0,1.5,1.018844e+08,Venture - Series Unknown
1,1,1,infinite roots,Private,1.0,For Profit,"1,875",Active,"Biotechnology, Food and Beverage, Health Care,...",51-100,...,0.0,5.300000,0.000000,0.0,0.0,0.0,86661948.0,3.0,2.599858e+08,Series B
2,2,2,instagrid,Private,2.0,For Profit,"1,950",Active,"Energy, Manufacturing",101-250,...,0.0,3.411765,3.014828,0.0,0.0,0.0,137401184.0,1.5,2.061018e+08,Series C
3,3,3,isar aerospace,Private,3.0,For Profit,"2,015",Active,"Information Technology, Science and Engineerin...",251-500,...,0.0,5.000000,0.000000,0.0,0.0,0.0,350641701.0,4.0,1.402567e+09,Series C
4,4,4,sosafe cyber security awareness,Private,3.0,For Profit,"2,054",Active,"Information Technology, Privacy and Security, ...",251-500,...,0.0,0.000000,0.000000,0.0,0.0,0.0,73000000.0,4.0,2.920000e+08,Series B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2184,2184,2184,btc echo gmbh,Private,1.0,For Profit,"201,902",Active,"Blockchain and Cryptocurrency, Content and Pub...",11-50,...,0.0,0.000000,0.000000,0.0,0.0,0.0,145515.0,4.0,5.820600e+05,Seed
2185,2185,2185,swipy,Private,2.0,For Profit,"213,578",Closed,"Clothing and Apparel, Commerce and Shopping, C...",11-50,...,0.0,0.000000,0.000000,0.0,0.0,0.0,75000.0,1.5,1.125000e+05,Non-equity Assistance
2186,2186,2186,regional markt,Private,2.0,For Profit,"224,877",Closed,"Agriculture and Farming, Commerce and Shopping...",11-50,...,0.0,0.000000,0.000000,0.0,0.0,0.0,183876.0,2.0,3.677520e+05,Convertible Note
2187,2187,2187,avant classic,Private,1.0,For Profit,"335,005",Closed,"Internet Services, Media and Entertainment",11-50,...,0.0,0.000000,0.000000,0.0,0.0,0.0,50000.0,4.0,2.000000e+05,Seed
2188,2188,2188,appiris,Private,3.0,For Profit,"466,833",Active,"Advertising, Consumer Electronics, Hardware, I...",11-50,...,0.0,0.000000,0.000000,0.0,0.0,0.0,1371723.0,3.5,4.801030e+06,Venture - Series Unknown

In [7]:
data[data.total_funding_usd > 0] #out: 2184 rows × 72 columns

,index,Unnamed: 0,Organization Name,IPO Status,Number of Founders,Company Type,CB Rank (Company),Operating Status,Industry Groups,Number of Employees,...,a_to_seed_ratio,b_to_a_ratio,c_to_b_ratio,d_to_c_ratio,e_to_d_ratio,pe_to_e_ratio,total_funding_usd,industry_multiples,company_valuation,last_funding_type
0,0,0,air up,Private,5.0,For Profit,"1,347",Active,"Commerce and Shopping, Food and Beverage, Other",251-500,...,0.0,0.000000,0.000000,0.0,0.0,0.0,67922929.0,1.5,1.018844e+08,Venture - Series Unknown
1,1,1,infinite roots,Private,1.0,For Profit,"1,875",Active,"Biotechnology, Food and Beverage, Health Care,...",51-100,...,0.0,5.300000,0.000000,0.0,0.0,0.0,86661948.0,3.0,2.599858e+08,Series B
2,2,2,instagrid,Private,2.0,For Profit,"1,950",Active,"Energy, Manufacturing",101-250,...,0.0,3.411765,3.014828,0.0,0.0,0.0,137401184.0,1.5,2.061018e+08,Series C
3,3,3,isar aerospace,Private,3.0,For Profit,"2,015",Active,"Information Technology, Science and Engineerin...",251-500,...,0.0,5.000000,0.000000,0.0,0.0,0.0,350641701.0,4.0,1.402567e+09,Series C
4,4,4,sosafe cyber security awareness,Private,3.0,For Profit,"2,054",Active,"Information Technology, Privacy and Security, ...",251-500,...,0.0,0.000000,0.000000,0.0,0.0,0.0,73000000.0,4.0,2.920000e+08,Series B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2184,2184,2184,btc echo gmbh,Private,1.0,For Profit,"201,902",Active,"Blockchain and Cryptocurrency, Content and Pub...",11-50,...,0.0,0.000000,0.000000,0.0,0.0,0.0,145515.0,4.0,5.820600e+05,Seed
2185,2185,2185,swipy,Private,2.0,For Profit,"213,578",Closed,"Clothing and Apparel, Commerce and Shopping, C...",11-50,...,0.0,0.000000,0.000000,0.0,0.0,0.0,75000.0,1.5,1.125000e+05,Non-equity Assistance
2186,2186,2186,regional markt,Private,2.0,For Profit,"224,877",Closed,"Agriculture and Farming, Commerce and Shopping...",11-50,...,0.0,0.000000,0.000000,0.0,0.0,0.0,183876.0,2.0,3.677520e+05,Convertible Note
2187,2187,2187,avant classic,Private,1.0,For Profit,"335,005",Closed,"Internet Services, Media and Entertainment",11-50,...,0.0,0.000000,0.000000,0.0,0.0,0.0,50000.0,4.0,2.000000e+05,Seed
2188,2188,2188,appiris,Private,3.0,For Profit,"466,833",Active,"Advertising, Consumer Electronics, Hardware, I...",11-50,...,0.0,0.000000,0.000000,0.0,0.0,0.0,1371723.0,3.5,4.801030e+06,Venture - Series Unknown

In [10]:
data.head()

,index,Unnamed: 0,Organization Name,IPO Status,Number of Founders,Company Type,CB Rank (Company),Operating Status,Industry Groups,Number of Employees,Estimated Revenue Range,Number of Exits,Number of Sub-Orgs,city,state,funding_status,revenue_range,no_employees,no_founders,industry_groups,website,phone,email,linkedin,twitter,facebook,articles,founded_year,last_funding_year,exit_year,closed_year,no_investors,no_fund_rounds,acquired,private_ipo,company_type,operting_status,no_lead_investors,no_sub_orgs,no_exits,has_preseed,has_seed,has_series_a,has_series_b,has_series_c,has_series_d,has_series_e,has_angel,has_debt_financing,has_grant,has_corporate_round,has_series_x,has_other_funding,preseed_fund,seed_fund,series_a_fund,series_b_fund,series_c_fund,series_d_fund,series_e_fund,private_equity_fund,seed_to_pre_ratio,a_to_seed_ratio,b_to_a_ratio,c_to_b_ratio,d_to_c_ratio,e_to_d_ratio,pe_to_e_ratio,total_funding_usd,industry_multiples,company_valuation,last_funding_type
0,0,0,air up,Private,5.0,For Profit,"1,347",Active,"Commerce and Shopping, Food and Beverage, Other",251-500,$100M to $500M,NaN,NaN,Munich,Bayern,Venture - Series Unknown,$100M to $500M,251-500,5.0,Consumer Goods and Services,1,0,1,1,0,1,28.0,2018,2021.0,NaN,NaN,6.0,5.0,0,1,1,1,1.0,0.0,0.0,0,0,1,0,0,0,0,0,0,0,0,1,0,NaN,NaN,18000000.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,67922929.0,1.5,1.018844e+08,Venture - Series Unknown
1,1,1,infinite roots,Private,1.0,For Profit,"1,875",Active,"Biotechnology, Food and Beverage, Health Care,...",51-100,NaN,NaN,NaN,Hamburg,Hamburg,Series B,$1M to $10M,51-100,1.0,Health and Biotechnology,1,0,1,1,0,0,21.0,2018,2024.0,NaN,NaN,14.0,8.0,0,1,1,1,4.0,0.0,0.0,0,0,1,1,0,0,0,0,0,1,0,1,0,NaN,NaN,10000000.0,53000000.0,NaN,NaN,NaN,NaN,0.0,0.0,5.300000,0.000000,0.0,0.0,0.0,86661948.0,3.0,2.599858e+08,Series B
2,2,2,instagrid,Private,2.0,For Profit,"1,950",Active,"Energy, Manufacturing",101-250,$1M to $10M,NaN,NaN,Stuttgart,Baden-Wurttemberg,Series C,$1M to $10M,101-250,2.0,Industrial and Manufacturing,1,1,1,1,1,1,31.0,2018,2024.0,NaN,NaN,10.0,4.0,0,1,1,1,4.0,0.0,0.0,0,0,1,1,1,0,0,0,0,0,0,0,0,NaN,NaN,8500000.0,29000000.0,87430000.0,NaN,NaN,NaN,0.0,0.0,3.411765,3.014828,0.0,0.0,0.0,137401184.0,1.5,2.061018e+08,Series C
3,3,3,isar aerospace,Private,3.0,For Profit,"2,015",Active,"Information Technology, Science and Engineerin...",251-500,$10M to $50M,NaN,NaN,Munich,Bayern,Series C,$10M to $50M,251-500,3.0,Technology and Software,1,0,1,1,1,1,52.0,2018,2024.0,NaN,NaN,16.0,5.0,0,1,1,1,5.0,0.0,0.0,0,0,1,1,0,0,0,0,0,0,0,0,0,NaN,NaN,15000000.0,75000000.0,NaN,NaN,NaN,NaN,0.0,0.0,5.000000,0.000000,0.0,0.0,0.0,350641701.0,4.0,1.402567e+09,Series C
4,4,4,sosafe cyber security awareness,Private,3.0,For Profit,"2,054",Active,"Information Technology, Privacy and Security, ...",251-500,$50M to $100M,NaN,NaN,Köln,Nordrhein-Westfalen,Series B,$50M to $100M,251-500,3.0,Technology and Software,1,0,1,1,1,0,2.0,2018,2022.0,NaN,NaN,6.0,3.0,0,1,1,1,2.0,0.0,0.0,0,0,0,1,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,73000000.0,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,73000000.0,4.0,2.920000e+08,Series B

### Defining X and y

In [97]:
y = data.iloc[:, -4] # y = "total_funding_usd"
X = data.iloc[:, 26:-4] #we've dropped first 25 columns b/c not numerical and we dropped last 3 columns for simplicity sake
X.shape

(2189, 42)

# Simple Data Preprocessing

### Changing dtypes

In [34]:
# 1 column (articles) is still object type and thus has to be converted to int for the scaler to work
X['articles'] = X['articles'].str.replace(',', '')
X['articles'] = X['articles'].astype(float).astype(int)

### Checking NANs, imputing cloumns with few NANs, dropping columns with many NANs

In [90]:
# list with all cloumns with NANs
my_NAN_dict = {k: v for k, v in dict(X.isna().sum()).items() if v > 0}
my_NAN_dict

{'last_funding_year': 3,
 'exit_year': 1513,
 'closed_year': 1702,
 'no_fund_rounds': 3,
 'preseed_fund': 1459,
 'seed_fund': 896,
 'series_a_fund': 1191,
 'series_b_fund': 1510,
 'series_c_fund': 1659,
 'series_d_fund': 1709,
 'series_e_fund': 1733,
 'private_equity_fund': 1718}

In [93]:
# Based on dict above, let's chose which columns to drop and which columns to impute
columns_to_drop = ['exit_year', 'closed_year', 'preseed_fund', 'seed_fund', 'series_a_fund', 'series_b_fund', 'series_c_fund', 'series_d_fund', 'series_e_fund', 'private_equity_fund']
columns_to_impute = ['last_funding_year', 'no_fund_rounds']

In [99]:
# Dropping the columns specified above
X.drop(columns=columns_to_drop,inplace=True)

(2189, 32)

In [101]:
# Imputing the columns specified above
imputer1 = SimpleImputer(strategy = "most_frequent")
imputer1.fit(X[['last_funding_year']])
X['last_funding_year'] = imputer1.transform(X[['last_funding_year']])

imputer2 = SimpleImputer(strategy = "most_frequent")
imputer2.fit(X[['no_fund_rounds']])
X['no_fund_rounds'] = imputer2.transform(X[['no_fund_rounds']])

In [102]:
#Final check: make sure that everything above worked and that we really don't have any NANs left
{k: v for k, v in dict(X.isna().sum()).items() if v > 0}

{}

### Train/validation/test split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.20, random_state=1)

#### Scaling the features

In [56]:
mm_scaler = MinMaxScaler()
mm_scaler.fit(X_train)

X_train_scaled = mm_scaler.transform(X_train)
X_test_scaled = mm_scaler.transform(X_test)