In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../raw_data/final_datav2.csv", low_memory=False)
data.reset_index(inplace=True)

In [3]:
data = data.drop_duplicates()
data = data[data.total_funding_usd > 0]
data

,index,Unnamed: 0,Organization Name,IPO Status,Number of Founders,Company Type,CB Rank (Company),Operating Status,Industry Groups,Number of Employees,...,b_to_a_ratio,c_to_b_ratio,d_to_c_ratio,e_to_d_ratio,pe_to_e_ratio,total_funding_usd,has_ico,last_funding_type,last_funding_amount,hub_tags
0,0,0,air up,Private,5.0,For Profit,"1,347",Active,"Commerce and Shopping, Food and Beverage, Other",251-500,...,0.000000,0.000000,0.0,0.0,0.0,67922929.0,0,Venture - Series Unknown,46744589.0,NaN
1,1,1,infinite roots,Private,1.0,For Profit,"1,875",Active,"Biotechnology, Food and Beverage, Health Care,...",51-100,...,5.300000,0.000000,0.0,0.0,0.0,86661948.0,0,Series B,57481860.0,NaN
2,2,2,instagrid,Private,2.0,For Profit,"1,950",Active,"Energy, Manufacturing",101-250,...,3.411765,3.014828,0.0,0.0,0.0,137401184.0,0,Series C,94927569.0,NaN
3,3,3,isar aerospace,Private,3.0,For Profit,"2,015",Active,"Information Technology, Science and Engineerin...",251-500,...,5.000000,0.000000,0.0,0.0,0.0,350641701.0,0,Series C,NaN,NaN
4,4,4,sosafe cyber security awareness,Private,3.0,For Profit,"2,054",Active,"Information Technology, Privacy and Security, ...",251-500,...,0.000000,0.000000,0.0,0.0,0.0,73000000.0,0,Series B,73000000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2184,2184,2184,btc echo gmbh,Private,1.0,For Profit,"201,902",Active,"Blockchain and Cryptocurrency, Content and Pub...",11-50,...,0.000000,0.000000,0.0,0.0,0.0,145515.0,0,Seed,NaN,NaN
2185,2185,2185,swipy,Private,2.0,For Profit,"213,578",Closed,"Clothing and Apparel, Commerce and Shopping, C...",11-50,...,0.000000,0.000000,0.0,0.0,0.0,75000.0,0,Non-equity Assistance,NaN,NaN
2186,2186,2186,regional markt,Private,2.0,For Profit,"224,877",Closed,"Agriculture and Farming, Commerce and Shopping...",11-50,...,0.000000,0.000000,0.0,0.0,0.0,183876.0,0,Convertible Note,72797.0,NaN
2187,2187,2187,avant classic,Private,1.0,For Profit,"335,005",Closed,"Internet Services, Media and Entertainment",11-50,...,0.000000,0.000000,0.0,0.0,0.0,50000.0,0,Seed,50000.0,NaN
2188,2188,2188,appiris,Private,3.0,For Profit,"466,833",Active,"Advertising, Consumer Electronics, Hardware, I...",11-50,...,0.000000,0.000000,0.0,0.0,0.0,1371723.0,0,Venture - Series Unknown,1371723.0,NaN

In [4]:
df = data.iloc[:, 13:]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2178 entries, 0 to 2188
Data columns (total 64 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   city                       2178 non-null   object
 1   state                      2178 non-null   object
 2   funding_status             2178 non-null   object
 3   revenue_range              2178 non-null   object
 4   no_employees               2178 non-null   object
 5   no_founders                2178 non-null   float64
 6   industry_groups            2178 non-null   object
 7   industry_groups_secondary  2178 non-null   object
 8   industry_groups_third      2178 non-null   object
 9   industry_groups_four       2178 non-null   object
 10  industry_groups_five       2178 non-null   object
 11  website                    2178 non-null   int64
 12  phone                      2178 non-null   int64
 13  email                      2178 non-null   int64
 14  linkedin                   2178 non-null   int64
 15  twitter                    2178 non-null   int64
 16  facebook                   2178 non-null   int64
 17  articles                   2178 non-null   object
 18  founded_year               2178 non-null   int64
 19  last_funding_year          2178 non-null   float64
 20  exit_year                  305 non-null    float64
 21  closed_year                56 non-null     float64
 22  no_investors               2178 non-null   float64
 23  no_fund_rounds             2178 non-null   float64
 24  acquired                   2178 non-null   int64
 25  private_ipo                2178 non-null   int64
 26  company_type               2178 non-null   int64
 27  operting_status            2178 non-null   int64
 28  no_lead_investors          2178 non-null   float64
 29  no_sub_orgs                2178 non-null   float64
 30  no_exits                   2178 non-null   float64
 31  has_preseed                2178 non-null   int64
 32  has_seed                   2178 non-null   int64
 33  has_series_a               2178 non-null   int64
 34  has_series_b               2178 non-null   int64
 35  has_series_c               2178 non-null   int64
 36  has_series_d               2178 non-null   int64
 37  has_series_e               2178 non-null   int64
 38  has_angel                  2178 non-null   int64
 39  has_debt_financing         2178 non-null   int64
 40  has_grant                  2178 non-null   int64
 41  has_corporate_round        2178 non-null   int64
 42  has_series_x               2178 non-null   int64
 43  has_other_funding          2178 non-null   int64
 44  preseed_fund               364 non-null    float64
 45  seed_fund                  1044 non-null   float64
 46  series_a_fund              693 non-null    float64
 47  series_b_fund              303 non-null    float64
 48  series_c_fund              118 non-null    float64
 49  series_d_fund              52 non-null     float64
 50  series_e_fund              24 non-null     float64
 51  private_equity_fund        45 non-null     float64
 52  seed_to_pre_ratio          2178 non-null   float64
 53  a_to_seed_ratio            2178 non-null   float64
 54  b_to_a_ratio               2178 non-null   float64
 55  c_to_b_ratio               2178 non-null   float64
 56  d_to_c_ratio               2178 non-null   float64
 57  e_to_d_ratio               2178 non-null   float64
 58  pe_to_e_ratio              2178 non-null   float64
 59  total_funding_usd          2178 non-null   float64
 60  has_ico                    2178 non-null   int64
 61  last_funding_type          2178 non-null   object
 62  last_funding_amount        1842 non-null   float64
 63  hub_tags                   51 non-null     object
dtypes: float64(26), int64(25), object(13)
memory usage: 1.1+ MB

In [6]:
df.funding_status

0       Early Stage Venture
1       Early Stage Venture
2        Late Stage Venture
3        Late Stage Venture
4       Early Stage Venture
               ...
2184                   Seed
2185                   Seed
2186                   Seed
2187                   Seed
2188                    M&A
Name: funding_status, Length: 2178, dtype: object

In [7]:
successful_public_ipo = list(df[df.private_ipo == 0].index)

In [8]:
successful_ma = list(df[df.funding_status == "M&A"].index)

In [9]:
successful_ipo = list(df[df.funding_status == "IPO"].index)

In [10]:
successful_pe_fu = list(df[df.funding_status == "Private Equity"].index)

In [11]:
successful_exit = list(df[df.exit_year > 1000].index)

In [12]:
successful_acquired = list(df[df.acquired > 0].index)

In [13]:
successful_d = list(df[df.has_series_d > 0].index)

In [14]:
successful_e = list(df[df.has_series_e > 0].index)

In [15]:
successful_pe = list(df[df.private_equity_fund > 1000000].index)

In [16]:
success_pre = list(df[df.seed_to_pre_ratio > 2.3].index)

In [17]:
success_seed = list(df[df.a_to_seed_ratio > 2.2].index)

In [18]:
success_a = list(df[df.b_to_a_ratio > 1.7].index)

In [19]:
success_b = list(df[df.c_to_b_ratio > 1.4].index)

In [20]:
df[df.c_to_b_ratio > 1.4]

,city,state,funding_status,revenue_range,no_employees,no_founders,industry_groups,industry_groups_secondary,industry_groups_third,industry_groups_four,...,b_to_a_ratio,c_to_b_ratio,d_to_c_ratio,e_to_d_ratio,pe_to_e_ratio,total_funding_usd,has_ico,last_funding_type,last_funding_amount,hub_tags
2,Stuttgart,Baden-Wurttemberg,Late Stage Venture,$1M to $10M,101-250,2.0,Energy and Natural Resources,Manufacturing and Industry,-1,-1,...,3.411765,3.014828,0.000000,0.0,0.0,137401184.0,0,Series C,94927569.0,NaN
5,Dresden,Sachsen,Late Stage Venture,$1M to $10M,101-250,8.0,Technology and Software,Hardware and Electronics,Technology and Software,Business Services,...,5.000000,2.800000,0.000000,0.0,0.0,122184409.0,0,Series C,84000000.0,NaN
7,Munich,Bayern,IPO,Less than $1M,101-250,4.0,Healthcare and Biotechnology,Healthcare and Biotechnology,Science and Engineering,-1,...,1.686275,2.162791,1.688172,0.0,0.0,522100000.0,0,Post-IPO Debt,175000000.0,Exited Unicorn
88,Berlin,Berlin,Late Stage Venture,$100M to $500M,251-500,2.0,Education and Training,Technology and Software,-1,-1,...,3.809524,2.500000,0.000000,0.0,0.0,333490482.0,0,Series C,200000000.0,NaN
92,Berlin,Berlin,Late Stage Venture,$100M to $500M,101-250,2.0,Technology and Software,Telecommunications and Internet Services,Other,Technology and Software,...,8.333333,4.000000,0.000000,0.0,0.0,308000000.0,1,Initial Coin Offering,50000000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2030,Munich,Bayern,Late Stage Venture,Less than $1M,101-250,2.0,Healthcare and Biotechnology,Technology and Software,-1,-1,...,0.000000,1.533333,0.000000,0.0,0.0,65772234.0,0,Series C,24533176.0,NaN
2032,Munich,Bayern,Late Stage Venture,$10M to $50M,101-250,5.0,Technology and Software,Technology and Software,Technology and Software,Science and Engineering,...,0.000000,5.652174,0.000000,0.0,0.0,130614117.0,0,Series C,78980207.0,NaN
2034,Berlin,Berlin,Late Stage Venture,$10M to $50M,101-250,2.0,Retail and E-commerce,Transportation and Logistics,-1,-1,...,2.461538,2.500000,0.000000,0.0,0.0,65798538.0,0,Venture - Series Unknown,NaN,NaN
2041,Berlin,Berlin,Late Stage Venture,$10M to $50M,101-250,2.0,Technology and Software,Retail and E-commerce,-1,-1,...,2.666667,2.225000,0.000000,0.0,0.0,33970218.0,0,Series C,20989749.0,NaN
2098,Berlin,Berlin,Early Stage Venture,$1M to $10M,101-250,4.0,Technology and Software,Business Services,Technology and Software,-1,...,2.031250,1.423077,0.000000,0.0,0.0,92215781.0,0,Undisclosed,NaN,NaN

In [21]:
success_unicorn = list(df[df["hub_tags"] == "Unicorn"].index)
success_emerging_unicorn = list(df[df["hub_tags"] == "Emerging Unicorn"].index)

In [22]:
success_target = successful_public_ipo + \
                successful_ma + \
                successful_ipo + \
                successful_pe_fu + \
                successful_exit + \
                successful_acquired + \
                success_unicorn + \
                success_emerging_unicorn
secondary_success = successful_d + \
                successful_e + \
                successful_pe + \
                success_pre + \
                success_seed + \
                success_a + \
                success_b
len(set(success_target))

433

In [23]:
len(set(secondary_success))

518

In [24]:
len(set(success_target + secondary_success))

801

In [25]:
closed_companies = df[df.closed_year > 0]
closed_companies = closed_companies[closed_companies.acquired == 0]
failed_seed = list(closed_companies[closed_companies.funding_status == "Seed"].index)

In [26]:
failed_early = list(closed_companies[closed_companies.funding_status == "Early Stage Venture"].index)

In [27]:
fail_pre = df[df.seed_to_pre_ratio < 2.3]
fail_pre = list(fail_pre[fail_pre.seed_to_pre_ratio > 0].index)

In [28]:
fail_seed = df[df.a_to_seed_ratio < 2.2]
fail_seed = list(fail_seed[fail_seed.a_to_seed_ratio > 0].index)

In [29]:
fail_a = df[df.b_to_a_ratio < 1.7] 
fail_a = list(fail_a[fail_a.b_to_a_ratio > 0].index)

In [30]:
fail_b = df[df.c_to_b_ratio < 1.4]   
fail_b = list(fail_b[fail_b.c_to_b_ratio > 0].index)

In [31]:
failure_target = failed_seed + failed_early
failure_secondary = fail_pre + fail_seed + fail_a + fail_b

In [32]:
len(set(failure_target))

23

In [33]:
both_ways = []
for i in failure_secondary:
    if i in secondary_success:
        both_ways.append(i)
len(both_ways)

84

In [34]:
both_way = []
for i in failure_target:
    if i in success_target:
        both_way.append(i)
len(both_way)

0

In [35]:
df["y"] = 2

In [36]:
df.loc[list(set(success_target)), ["y"]] = 1

In [37]:
df.loc[list(set(failure_target)), ["y"]] = 0

In [38]:
df[df["y"] > 1]

,city,state,funding_status,revenue_range,no_employees,no_founders,industry_groups,industry_groups_secondary,industry_groups_third,industry_groups_four,...,c_to_b_ratio,d_to_c_ratio,e_to_d_ratio,pe_to_e_ratio,total_funding_usd,has_ico,last_funding_type,last_funding_amount,hub_tags,y
0,Munich,Bayern,Early Stage Venture,$100M to $500M,251-500,5.0,Retail and E-commerce,Consumer Products,Other,-1,...,0.000000,0.0,0.0,0.0,67922929.0,0,Venture - Series Unknown,46744589.0,NaN,2
1,Hamburg,Hamburg,Early Stage Venture,$1M to $10M,51-100,1.0,Healthcare and Biotechnology,Consumer Products,Healthcare and Biotechnology,Science and Engineering,...,0.000000,0.0,0.0,0.0,86661948.0,0,Series B,57481860.0,NaN,2
2,Stuttgart,Baden-Wurttemberg,Late Stage Venture,$1M to $10M,101-250,2.0,Energy and Natural Resources,Manufacturing and Industry,-1,-1,...,3.014828,0.0,0.0,0.0,137401184.0,0,Series C,94927569.0,NaN,2
3,Munich,Bayern,Late Stage Venture,$10M to $50M,251-500,3.0,Technology and Software,Science and Engineering,Transportation and Logistics,-1,...,0.000000,0.0,0.0,0.0,350641701.0,0,Series C,NaN,NaN,2
4,Köln,Nordrhein-Westfalen,Early Stage Venture,$50M to $100M,251-500,3.0,Technology and Software,Technology and Software,Technology and Software,-1,...,0.000000,0.0,0.0,0.0,73000000.0,0,Series B,73000000.0,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2180,Mannheim,Baden-Wurttemberg,Seed,$1M to $10M,11-50,1.0,Technology and Software,Business Services,Transportation and Logistics,-1,...,0.000000,0.0,0.0,0.0,27284.0,0,Seed,27284.0,NaN,2
2181,Dreieich,Hessen,Seed,Less than $1M,11-50,1.0,Business Services,-1,-1,-1,...,0.000000,0.0,0.0,0.0,81868.0,0,Grant,81868.0,NaN,2
2184,Berlin,Berlin,Seed,$1M to $10M,11-50,1.0,Technology and Software,Media and Entertainment,Technology and Software,Business Services,...,0.000000,0.0,0.0,0.0,145515.0,0,Seed,NaN,NaN,2
2185,Butzbach,Hessen,Seed,$1M to $10M,11-50,2.0,Consumer Products,Retail and E-commerce,Community and Lifestyle,Business Services,...,0.000000,0.0,0.0,0.0,75000.0,0,Non-equity Assistance,NaN,NaN,2
2187,Berlin,Berlin,Seed,$1M to $10M,11-50,1.0,Telecommunications and Internet Services,Media and Entertainment,-1,-1,...,0.000000,0.0,0.0,0.0,50000.0,0,Seed,50000.0,NaN,2

In [39]:
df[df["y"] == 1]

,city,state,funding_status,revenue_range,no_employees,no_founders,industry_groups,industry_groups_secondary,industry_groups_third,industry_groups_four,...,c_to_b_ratio,d_to_c_ratio,e_to_d_ratio,pe_to_e_ratio,total_funding_usd,has_ico,last_funding_type,last_funding_amount,hub_tags,y
6,Gilching,Bayern,M&A,$50M to $100M,501-1000,3.0,Technology and Software,Technology and Software,Hardware and Electronics,Manufacturing and Industry,...,0.000000,0.000000,0.0,0.0,270050589.0,0,Venture - Series Unknown,30000000.0,Unicorn,1
7,Munich,Bayern,IPO,Less than $1M,101-250,4.0,Healthcare and Biotechnology,Healthcare and Biotechnology,Science and Engineering,-1,...,2.162791,1.688172,0.0,0.0,522100000.0,0,Post-IPO Debt,175000000.0,Exited Unicorn,1
20,Berlin,Berlin,IPO,$10M to $50M,101-250,3.0,Energy and Natural Resources,Energy and Natural Resources,Technology and Software,Energy and Natural Resources,...,0.000000,0.000000,0.0,0.0,132246582.0,0,Post-IPO Debt,26671161.0,NaN,1
34,Wiesbaden,Hessen,Private Equity,$1M to $10M,11-50,1.0,Manufacturing and Industry,Manufacturing and Industry,-1,-1,...,0.000000,0.000000,0.0,0.0,227276085.0,0,Private Equity,227276084.0,NaN,1
35,Munich,Bayern,M&A,$1M to $10M,51-100,3.0,Retail and E-commerce,Other,Transportation and Logistics,-1,...,0.000000,0.000000,0.0,0.0,190190966.0,0,Debt Financing,154190965.0,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2156,Düsseldorf,Nordrhein-Westfalen,M&A,$10M to $50M,101-250,2.0,Retail and E-commerce,Finance and Payments,Telecommunications and Internet Services,Business Services,...,0.000000,0.000000,0.0,0.0,50856135.0,0,Secondary Market,50856134.0,NaN,1
2170,Berlin,Berlin,M&A,$1M to $10M,11-50,2.0,Technology and Software,Telecommunications and Internet Services,Media and Entertainment,-1,...,0.000000,0.000000,0.0,0.0,1441367.0,0,Non-equity Assistance,537004.0,NaN,1
2175,Berlin,Berlin,M&A,$1M to $10M,11-50,3.0,Hardware and Electronics,Hardware and Electronics,-1,-1,...,0.000000,0.000000,0.0,0.0,6745373.0,0,Series A,NaN,NaN,1
2182,Berlin,Berlin,M&A,Less than $1M,11-50,2.0,Technology and Software,Business Services,Media and Entertainment,Telecommunications and Internet Services,...,0.000000,0.000000,0.0,0.0,129685.0,0,Grant,129684.0,NaN,1
2188,Berlin,Berlin,M&A,Less than $1M,11-50,3.0,Business Services,Hardware and Electronics,Hardware and Electronics,Telecommunications and Internet Services,...,0.000000,0.000000,0.0,0.0,1371723.0,0,Venture - Series Unknown,1371723.0,NaN,1

In [40]:
df[df["y"] == 0]

,city,state,funding_status,revenue_range,no_employees,no_founders,industry_groups,industry_groups_secondary,industry_groups_third,industry_groups_four,...,c_to_b_ratio,d_to_c_ratio,e_to_d_ratio,pe_to_e_ratio,total_funding_usd,has_ico,last_funding_type,last_funding_amount,hub_tags,y
166,Berlin,Berlin,Seed,Less than $1M,11-50,2.0,Technology and Software,Telecommunications and Internet Services,Technology and Software,Community and Lifestyle,...,0.0,0.0,0.0,0.0,1012483.0,0,Pre-Seed,543055.0,NaN,0
204,Düsseldorf,Nordrhein-Westfalen,Seed,$1M to $10M,11-50,1.0,Technology and Software,Technology and Software,Telecommunications and Internet Services,Media and Entertainment,...,0.0,0.0,0.0,0.0,192000.0,0,Grant,27000.0,NaN,0
205,Berlin,Berlin,Seed,$1M to $10M,11-50,4.0,Business Services,Technology and Software,Technology and Software,Education and Training,...,0.0,0.0,0.0,0.0,215406.0,0,Grant,154730.0,NaN,0
443,Berlin,Berlin,Seed,$1M to $10M,1001-5000,2.0,Retail and E-commerce,Consumer Products,Telecommunications and Internet Services,Transportation and Logistics,...,0.0,0.0,0.0,0.0,6777697.0,0,Angel,5694229.0,NaN,0
467,Berlin,Berlin,Seed,$1M to $10M,11-50,1.0,Hardware and Electronics,Telecommunications and Internet Services,Science and Engineering,Technology and Software,...,0.0,0.0,0.0,0.0,3900000.0,0,Seed,3900000.0,NaN,0
553,Berlin,Berlin,Seed,$10M to $50M,11-50,3.0,Technology and Software,Telecommunications and Internet Services,Media and Entertainment,Telecommunications and Internet Services,...,0.0,0.0,0.0,0.0,12200000.0,0,Seed,11000000.0,NaN,0
634,Hamburg,Hamburg,Seed,$1M to $10M,11-50,2.0,Consumer Products,Retail and E-commerce,Business Services,Finance and Payments,...,0.0,0.0,0.0,0.0,3166420.0,0,Seed,2102388.0,NaN,0
689,Berlin,Berlin,Seed,Less than $1M,11-50,3.0,Technology and Software,Telecommunications and Internet Services,Other,Technology and Software,...,0.0,0.0,0.0,0.0,55092.0,0,Pre-Seed,55092.0,NaN,0
921,Berlin,Berlin,Seed,Less than $1M,11-50,1.0,Technology and Software,Finance and Payments,Other,Finance and Payments,...,0.0,0.0,0.0,0.0,100000.0,0,Pre-Seed,80000.0,NaN,0
925,Berlin,Berlin,Seed,$1M to $10M,11-50,3.0,Technology and Software,Telecommunications and Internet Services,Media and Entertainment,Telecommunications and Internet Services,...,0.0,0.0,0.0,0.0,807961.0,0,Pre-Seed,588928.0,NaN,0
1010,Berlin,Berlin,Seed,$1M to $10M,11-50,3.0,Telecommunications and Internet Services,Technology and Software,Retail and E-commerce,Technology and Software,...,0.0,0.0,0.0,0.0,250000.0,0,Angel,250000.0,NaN,0
1014,Hamburg,Hamburg,Seed,Less than $1M,11-50,3.0,Telecommunications and Internet Services,Media and Entertainment,-1,-1,...,0.0,0.0,0.0,0.0,34474532.0,0,Corporate Round,34474532.0,NaN,0
1190,Hamburg,Hamburg,Early Stage Venture,$1M to $10M,11-50,3.0,Business Services,Manufacturing and Industry,Science and Engineering,Energy and Natural Resources,...,0.0,0.0,0.0,0.0,11209814.0,0,Series A,9273753.0,NaN,0
1257,Berlin,Berlin,Early Stage Venture,$1M to $10M,11-50,2.0,Consumer Products,Healthcare and Biotechnology,-1,-1,...,0.0,0.0,0.0,0.0,5387459.0,0,Series A,2802376.0,NaN,0
1321,Berlin,Berlin,Seed,Less than $1M,11-50,3.0,Technology and Software,Retail and E-commerce,Telecommunications and Internet Services,Technology and Software,...,0.0,0.0,0.0,0.0,1781225.0,0,Seed,1736565.0,NaN,0
1727,München,Bayern,Seed,$1M to $10M,11-50,3.0,Hardware and Electronics,Education and Training,Hardware and Electronics,Technology and Software,...,0.0,0.0,0.0,0.0,1244693.0,0,Product Crowdfunding,659661.0,NaN,0
1730,Berlin,Berlin,Seed,$1M to $10M,11-50,3.0,Hardware and Electronics,Media and Entertainment,Hardware and Electronics,Media and Entertainment,...,0.0,0.0,0.0,0.0,3473295.0,0,Venture - Series Unknown,NaN,NaN,0
2095,Berlin,Berlin,Early Stage Venture,$1M to $10M,11-50,5.0,Finance and Payments,Finance and Payments,-1,-1,...,0.0,0.0,0.0,0.0,5163389.0,0,Series A,3163389.0,NaN,0
2148,Prenzlauer Berg,Berlin,Seed,$1M to $10M,11-50,3.0,Technology and Software,Technology and Software,-1,-1,...,0.0,0.0,0.0,0.0,4182824.0,0,Seed,4182823.0,NaN,0
2163,Bonn,Nordrhein-Westfalen,Seed,$1M to $10M,11-50,1.0,Consumer Products,Retail and E-commerce,Community and Lifestyle,Business Services,...,0.0,0.0,0.0,0.0,1703939.0,0,Equity Crowdfunding,1703939.0,NaN,0
2164,Kreuzberg,Berlin,Early Stage Venture,$1M to $10M,11-50,1.0,Retail and E-commerce,Consumer Products,Telecommunications and Internet Services,Transportation and Logistics,...,0.0,0.0,0.0,0.0,3644307.0,0,Series A,3644306.0,NaN,0
2183,Berlin,Berlin,Early Stage Venture,$1M to $10M,11-50,2.0,Technology and Software,Government and Public Services,Technology and Software,Technology and Software,...,0.0,0.0,0.0,0.0,5015405.0,0,Venture - Series Unknown,NaN,NaN,0
2186,Munich,Bayern,Seed,$1M to $10M,11-50,2.0,Manufacturing and Industry,Retail and E-commerce,Telecommunications and Internet Services,Other,...,0.0,0.0,0.0,0.0,183876.0,0,Convertible Note,72797.0,NaN,0

In [41]:
failure_secondary = [x for x in failure_secondary if x not in both_ways]
failure_secondary = [x for x in failure_secondary if x not in success_target]
failure_secondary = [x for x in failure_secondary if x not in secondary_success]
failure_secondary = [x for x in failure_secondary if x not in failure_target]

In [42]:
secondary_success = [x for x in secondary_success if x not in both_ways]
secondary_success = [x for x in secondary_success if x not in failure_target]
secondary_success = [x for x in secondary_success if x not in failure_secondary]
secondary_success = [x for x in secondary_success if x not in success_target]

In [43]:
len(set(failure_secondary))

77

In [44]:
len(set(secondary_success))

322

In [45]:
df.loc[list(set(secondary_success)), ["y"]] = 1

In [46]:
df.loc[list(set(failure_secondary)), ["y"]] = 0

In [70]:
certain_list = list(df[df["y"] < 2].index)

In [48]:
undecided_list = [x for x in both_ways if x not in certain_list]

In [49]:
df[df["y"] < 2]

,city,state,funding_status,revenue_range,no_employees,no_founders,industry_groups,industry_groups_secondary,industry_groups_third,industry_groups_four,...,c_to_b_ratio,d_to_c_ratio,e_to_d_ratio,pe_to_e_ratio,total_funding_usd,has_ico,last_funding_type,last_funding_amount,hub_tags,y
1,Hamburg,Hamburg,Early Stage Venture,$1M to $10M,51-100,1.0,Healthcare and Biotechnology,Consumer Products,Healthcare and Biotechnology,Science and Engineering,...,0.000000,0.0,0.0,0.0,86661948.0,0,Series B,57481860.0,NaN,1
2,Stuttgart,Baden-Wurttemberg,Late Stage Venture,$1M to $10M,101-250,2.0,Energy and Natural Resources,Manufacturing and Industry,-1,-1,...,3.014828,0.0,0.0,0.0,137401184.0,0,Series C,94927569.0,NaN,1
3,Munich,Bayern,Late Stage Venture,$10M to $50M,251-500,3.0,Technology and Software,Science and Engineering,Transportation and Logistics,-1,...,0.000000,0.0,0.0,0.0,350641701.0,0,Series C,NaN,NaN,1
5,Dresden,Sachsen,Late Stage Venture,$1M to $10M,101-250,8.0,Technology and Software,Hardware and Electronics,Technology and Software,Business Services,...,2.800000,0.0,0.0,0.0,122184409.0,0,Series C,84000000.0,NaN,1
6,Gilching,Bayern,M&A,$50M to $100M,501-1000,3.0,Technology and Software,Technology and Software,Hardware and Electronics,Manufacturing and Industry,...,0.000000,0.0,0.0,0.0,270050589.0,0,Venture - Series Unknown,30000000.0,Unicorn,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2175,Berlin,Berlin,M&A,$1M to $10M,11-50,3.0,Hardware and Electronics,Hardware and Electronics,-1,-1,...,0.000000,0.0,0.0,0.0,6745373.0,0,Series A,NaN,NaN,1
2182,Berlin,Berlin,M&A,Less than $1M,11-50,2.0,Technology and Software,Business Services,Media and Entertainment,Telecommunications and Internet Services,...,0.000000,0.0,0.0,0.0,129685.0,0,Grant,129684.0,NaN,1
2183,Berlin,Berlin,Early Stage Venture,$1M to $10M,11-50,2.0,Technology and Software,Government and Public Services,Technology and Software,Technology and Software,...,0.000000,0.0,0.0,0.0,5015405.0,0,Venture - Series Unknown,NaN,NaN,0
2186,Munich,Bayern,Seed,$1M to $10M,11-50,2.0,Manufacturing and Industry,Retail and E-commerce,Telecommunications and Internet Services,Other,...,0.000000,0.0,0.0,0.0,183876.0,0,Convertible Note,72797.0,NaN,0
2188,Berlin,Berlin,M&A,Less than $1M,11-50,3.0,Business Services,Hardware and Electronics,Hardware and Electronics,Telecommunications and Internet Services,...,0.000000,0.0,0.0,0.0,1371723.0,0,Venture - Series Unknown,1371723.0,NaN,1

In [51]:
df.columns

Index(['city', 'state', 'funding_status', 'revenue_range', 'no_employees',
       'no_founders', 'industry_groups', 'industry_groups_secondary',
       'industry_groups_third', 'industry_groups_four', 'industry_groups_five',
       'website', 'phone', 'email', 'linkedin', 'twitter', 'facebook',
       'articles', 'founded_year', 'last_funding_year', 'exit_year',
       'closed_year', 'no_investors', 'no_fund_rounds', 'acquired',
       'private_ipo', 'company_type', 'operting_status', 'no_lead_investors',
       'no_sub_orgs', 'no_exits', 'has_preseed', 'has_seed', 'has_series_a',
       'has_series_b', 'has_series_c', 'has_series_d', 'has_series_e',
       'has_angel', 'has_debt_financing', 'has_grant', 'has_corporate_round',
       'has_series_x', 'has_other_funding', 'preseed_fund', 'seed_fund',
       'series_a_fund', 'series_b_fund', 'series_c_fund', 'series_d_fund',
       'series_e_fund', 'private_equity_fund', 'seed_to_pre_ratio',
       'a_to_seed_ratio', 'b_to_a_ratio', 'c_to_b_ratio', 'd_to_c_ratio',
       'e_to_d_ratio', 'pe_to_e_ratio', 'total_funding_usd', 'has_ico',
       'last_funding_type', 'last_funding_amount', 'hub_tags', 'y'],
      dtype='object')

In [52]:
y = [
    "exit_year", "closed_year", "acquired", "funding_status", "has_series_d", "has_series_e"
]

Pre-Seed: $50,000 - $500,000
Seed: $500,000 - $2 Millionen
Series A: $2 Millionen - $15 Millionen
Series B: $15 Millionen - $50 Millionen
Series C: $50 Millionen - $100 Millionen
Series D: $100 Millionen - $200 Millionen
Series E und darüber hinaus: $200 Millionen und mehr

In [72]:
export_df = df.loc[:, ['state', 'funding_status', 'revenue_range', 'no_employees',
       'no_founders', 'industry_groups', 'website', 'phone', 'email',
       'linkedin', 'twitter', 'facebook', 'founded_year','no_investors', 'no_fund_rounds', 'private_ipo', 'company_type',
       'operting_status', 'no_lead_investors', 'no_sub_orgs',
       'has_preseed', 'has_seed', 'has_series_a', 'has_series_b',
       'has_series_c', 'has_series_d', 'has_series_e', 'has_angel',
       'has_debt_financing', 'has_grant', 'has_corporate_round',
       'has_series_x', 'has_ico', 'total_funding_usd', 'y']]

In [73]:
export_df.to_csv("../raw_data/X_y_data1.csv")