In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../raw_data/final_datav6.csv", low_memory=False)
data.reset_index(inplace=True)

In [3]:
data = data.drop_duplicates()
data = data[data.total_funding_usd > 0]
data

,index,Unnamed: 0,Organization Name,IPO Status,Number of Founders,Company Type,CB Rank (Company),Operating Status,Industry Groups,Number of Employees,...,d_to_c_ratio,e_to_d_ratio,pe_to_e_ratio,total_funding_usd,last_funding_type,last_funding_amount,hub_tags,industry_multiples,company_valuation,months_since_founded
0,0,0,air up,Private,5.0,For Profit,"1,347",Active,"Commerce and Shopping, Food and Beverage, Other",251-500,...,0.0,0.0,0.0,67922929.0,Venture - Series Unknown,46744589.0,NaN,1.5,1.018844e+08,77
1,1,1,infinite roots,Private,1.0,For Profit,"1,875",Active,"Biotechnology, Food and Beverage, Health Care,...",51-100,...,0.0,0.0,0.0,86661948.0,Series B,57481860.0,NaN,3.0,2.599858e+08,77
2,2,2,instagrid,Private,2.0,For Profit,"1,950",Active,"Energy, Manufacturing",101-250,...,0.0,0.0,0.0,137401184.0,Series C,94927569.0,NaN,1.5,2.061018e+08,77
3,3,3,isar aerospace,Private,3.0,For Profit,"2,015",Active,"Information Technology, Science and Engineerin...",251-500,...,0.0,0.0,0.0,350641701.0,Series C,NaN,NaN,4.0,1.402567e+09,77
4,4,4,sosafe cyber security awareness,Private,3.0,For Profit,"2,054",Active,"Information Technology, Privacy and Security, ...",251-500,...,0.0,0.0,0.0,73000000.0,Series B,73000000.0,NaN,4.0,2.920000e+08,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2184,2184,2184,btc echo gmbh,Private,1.0,For Profit,"201,902",Active,"Blockchain and Cryptocurrency, Content and Pub...",11-50,...,0.0,0.0,0.0,145515.0,Seed,NaN,NaN,4.0,5.820600e+05,123
2185,2185,2185,swipy,Private,2.0,For Profit,"213,578",Closed,"Clothing and Apparel, Commerce and Shopping, C...",11-50,...,0.0,0.0,0.0,75000.0,Non-equity Assistance,NaN,NaN,1.5,1.125000e+05,116
2186,2186,2186,regional markt,Private,2.0,For Profit,"224,877",Closed,"Agriculture and Farming, Commerce and Shopping...",11-50,...,0.0,0.0,0.0,183876.0,Convertible Note,72797.0,NaN,2.0,3.677520e+05,125
2187,2187,2187,avant classic,Private,1.0,For Profit,"335,005",Closed,"Internet Services, Media and Entertainment",11-50,...,0.0,0.0,0.0,50000.0,Seed,50000.0,NaN,4.0,2.000000e+05,125
2188,2188,2188,appiris,Private,3.0,For Profit,"466,833",Active,"Advertising, Consumer Electronics, Hardware, I...",11-50,...,0.0,0.0,0.0,1371723.0,Venture - Series Unknown,1371723.0,NaN,3.5,4.801030e+06,125

In [4]:
df = data.iloc[:, 2:]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2184 entries, 0 to 2188
Data columns (total 78 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Organization Name        2184 non-null   object
 1   IPO Status               2184 non-null   object
 2   Number of Founders       1960 non-null   float64
 3   Company Type             2178 non-null   object
 4   CB Rank (Company)        2177 non-null   object
 5   Operating Status         2184 non-null   object
 6   Industry Groups          2169 non-null   object
 7   Number of Employees      2184 non-null   object
 8   Estimated Revenue Range  1633 non-null   object
 9   Number of Exits          12 non-null     float64
 10  Number of Sub-Orgs       39 non-null     float64
 11  city                     2184 non-null   object
 12  state                    2184 non-null   object
 13  funding_status           2184 non-null   object
 14  revenue_range            2184 non-null   object
 15  no_employees             2184 non-null   object
 16  lat                      2183 non-null   float64
 17  lon                      2183 non-null   float64
 18  no_founders              2184 non-null   float64
 19  industry                 2184 non-null   object
 20  industry_groups          2184 non-null   object
 21  industry_groups_andreas  2184 non-null   object
 22  website                  2184 non-null   int64
 23  phone                    2184 non-null   int64
 24  email                    2184 non-null   int64
 25  linkedin                 2184 non-null   int64
 26  twitter                  2184 non-null   int64
 27  facebook                 2184 non-null   int64
 28  articles                 2184 non-null   object
 29  founded_year             2184 non-null   int64
 30  last_funding_year        2181 non-null   float64
 31  exit_year                305 non-null    float64
 32  closed_year              56 non-null     float64
 33  no_investors             2184 non-null   float64
 34  no_fund_rounds           2181 non-null   float64
 35  acquired                 2184 non-null   int64
 36  private_ipo              2184 non-null   int64
 37  company_type             2184 non-null   int64
 38  operting_status          2184 non-null   int64
 39  no_lead_investors        2184 non-null   float64
 40  no_sub_orgs              2184 non-null   float64
 41  no_exits                 2184 non-null   float64
 42  has_preseed              2184 non-null   int64
 43  has_seed                 2184 non-null   int64
 44  has_series_a             2184 non-null   int64
 45  has_series_b             2184 non-null   int64
 46  has_series_c             2184 non-null   int64
 47  has_series_d             2184 non-null   int64
 48  has_series_e             2184 non-null   int64
 49  has_angel                2184 non-null   int64
 50  has_debt_financing       2184 non-null   int64
 51  has_grant                2184 non-null   int64
 52  has_corporate_round      2184 non-null   int64
 53  has_series_x             2184 non-null   int64
 54  has_ico                  2184 non-null   int64
 55  has_other_funding        2184 non-null   int64
 56  preseed_fund             366 non-null    float64
 57  seed_fund                1047 non-null   float64
 58  series_a_fund            697 non-null    float64
 59  series_b_fund            303 non-null    float64
 60  series_c_fund            118 non-null    float64
 61  series_d_fund            52 non-null     float64
 62  series_e_fund            24 non-null     float64
 63  private_equity_fund      45 non-null     float64
 64  seed_to_pre_ratio        2184 non-null   float64
 65  a_to_seed_ratio          2184 non-null   float64
 66  b_to_a_ratio             2184 non-null   float64
 67  c_to_b_ratio             2184 non-null   float64
 68  d_to_c_ratio             2184 non-null   float64
 69  e_to_d_ratio             2184 non-null   float64
 70  pe_to_e_ratio            2184 non-null   float64
 71  total_funding_usd        2184 non-null   float64
 72  last_funding_type        2181 non-null   object
 73  last_funding_amount      1842 non-null   float64
 74  hub_tags                 51 non-null     object
 75  industry_multiples       2125 non-null   float64
 76  company_valuation        2125 non-null   float64
 77  months_since_founded     2184 non-null   int64
dtypes: float64(33), int64(26), object(19)
memory usage: 1.3+ MB

In [6]:
df.funding_status

0       Early Stage Venture
1       Early Stage Venture
2        Late Stage Venture
3        Late Stage Venture
4       Early Stage Venture
               ...
2184                   Seed
2185                   Seed
2186                   Seed
2187                   Seed
2188                    M&A
Name: funding_status, Length: 2184, dtype: object

In [7]:
successful_public_ipo = list(df[df.private_ipo == 0].index)

In [8]:
successful_ma = list(df[df.funding_status == "M&A"].index)

In [9]:
successful_ipo = list(df[df.funding_status == "IPO"].index)

In [10]:
successful_pe_fu = list(df[df.funding_status == "Private Equity"].index)

In [11]:
successful_exit = list(df[df.exit_year > 1000].index)

In [12]:
successful_acquired = list(df[df.acquired > 0].index)

In [13]:
successful_d = list(df[df.has_series_d > 0].index)

In [14]:
successful_e = list(df[df.has_series_e > 0].index)

In [15]:
successful_pe = list(df[df.private_equity_fund > 1000000].index)

In [16]:
success_pre = list(df[df.seed_to_pre_ratio > 2.3].index)

In [17]:
success_seed = list(df[df.a_to_seed_ratio > 2.2].index)

In [18]:
success_a = list(df[df.b_to_a_ratio > 1.7].index)

In [19]:
success_b = list(df[df.c_to_b_ratio > 1.4].index)

In [20]:
df[df.c_to_b_ratio > 1.4]

,Organization Name,IPO Status,Number of Founders,Company Type,CB Rank (Company),Operating Status,Industry Groups,Number of Employees,Estimated Revenue Range,Number of Exits,...,d_to_c_ratio,e_to_d_ratio,pe_to_e_ratio,total_funding_usd,last_funding_type,last_funding_amount,hub_tags,industry_multiples,company_valuation,months_since_founded
2,instagrid,Private,2.0,For Profit,"1,950",Active,"Energy, Manufacturing",101-250,$1M to $10M,NaN,...,0.000000,0.0,0.0,137401184.0,Series C,94927569.0,NaN,1.5,2.061018e+08,77
5,wandelbots,Private,8.0,For Profit,"2,128",Active,"Artificial Intelligence (AI), Consumer Electro...",101-250,$1M to $10M,NaN,...,0.000000,0.0,0.0,122184409.0,Series C,84000000.0,NaN,4.0,4.887376e+08,80
7,atai life sciences,Public,4.0,For Profit,"2,728",Active,"Biotechnology, Health Care, Science and Engine...",101-250,Less than $1M,2.0,...,1.688172,0.0,0.0,522100000.0,Post-IPO Debt,175000000.0,Exited Unicorn,3.0,1.566300e+09,77
88,coachhub,Private,2.0,For Profit,"31,104",Active,"Education, Software",251-500,$100M to $500M,NaN,...,0.000000,0.0,0.0,333490482.0,Series C,200000000.0,NaN,1.5,5.002357e+08,77
92,matter labs,Private,2.0,For Profit,"32,613",Active,"Blockchain and Cryptocurrency, Internet Servic...",101-250,NaN,NaN,...,0.000000,0.0,0.0,308000000.0,Initial Coin Offering,50000000.0,NaN,4.0,1.232000e+09,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2030,smart reporting,Private,2.0,For Profit,"4,292",Active,"Health Care, Software",101-250,Less than $1M,NaN,...,0.000000,0.0,0.0,65772234.0,Series C,24533176.0,NaN,3.0,1.973167e+08,125
2032,konux,Private,5.0,For Profit,"4,840",Active,"Artificial Intelligence (AI), Data and Analyti...",101-250,$10M to $50M,NaN,...,0.000000,0.0,0.0,130614117.0,Series C,78980207.0,NaN,4.0,5.224565e+08,123
2034,seven senders,Private,2.0,For Profit,"5,490",Active,"Commerce and Shopping, Transportation",101-250,$10M to $50M,NaN,...,0.000000,0.0,0.0,65798538.0,Venture - Series Unknown,NaN,NaN,1.5,9.869781e+07,115
2041,wunderflats,Private,2.0,For Profit,"8,275",Active,"Information Technology, Real Estate",101-250,$10M to $50M,NaN,...,0.000000,0.0,0.0,33970218.0,Series C,20989749.0,NaN,4.0,1.358809e+08,125
2098,zeotap,Private,4.0,For Profit,"48,151",Active,"Data and Analytics, Sales and Marketing, Software",101-250,$1M to $10M,NaN,...,0.000000,0.0,0.0,92215781.0,Undisclosed,NaN,NaN,4.0,3.688631e+08,117

In [21]:
success_unicorn = list(df[df["hub_tags"] == "Unicorn"].index)
success_emerging_unicorn = list(df[df["hub_tags"] == "Emerging Unicorn"].index)

In [22]:
success_target = successful_public_ipo + \
                successful_ma + \
                successful_ipo + \
                successful_pe_fu + \
                successful_exit + \
                successful_acquired + \
                success_unicorn + \
                success_emerging_unicorn
secondary_success = successful_d + \
                successful_e + \
                successful_pe + \
                success_pre + \
                success_seed + \
                success_a + \
                success_b
len(set(success_target))

434

In [23]:
len(set(secondary_success))

520

In [24]:
len(set(success_target + secondary_success))

804

In [25]:
closed_companies = df[df.closed_year > 0]
closed_companies = closed_companies[closed_companies.acquired == 0]
failed_seed = list(closed_companies[closed_companies.funding_status == "Seed"].index)

In [26]:
failed_early = list(closed_companies[closed_companies.funding_status == "Early Stage Venture"].index)

In [27]:
fail_pre = df[df.seed_to_pre_ratio < 2.3]
fail_pre = list(fail_pre[fail_pre.seed_to_pre_ratio > 0].index)

In [28]:
fail_seed = df[df.a_to_seed_ratio < 2.2]
fail_seed = list(fail_seed[fail_seed.a_to_seed_ratio > 0].index)

In [29]:
fail_a = df[df.b_to_a_ratio < 1.7] 
fail_a = list(fail_a[fail_a.b_to_a_ratio > 0].index)

In [30]:
fail_b = df[df.c_to_b_ratio < 1.4]   
fail_b = list(fail_b[fail_b.c_to_b_ratio > 0].index)

In [31]:
failure_target = failed_seed + failed_early
failure_secondary = fail_pre + fail_seed + fail_a + fail_b

In [32]:
len(set(failure_target))

23

In [33]:
both_ways = []
for i in failure_secondary:
    if i in secondary_success:
        both_ways.append(i)
len(both_ways)

85

In [34]:
both_way = []
for i in failure_target:
    if i in success_target:
        both_way.append(i)
len(both_way)

0

In [35]:
df["y"] = 2

In [36]:
df.loc[list(set(success_target)), ["y"]] = 1

In [37]:
df.loc[list(set(failure_target)), ["y"]] = 0

In [38]:
df[df["y"] > 1]

,Organization Name,IPO Status,Number of Founders,Company Type,CB Rank (Company),Operating Status,Industry Groups,Number of Employees,Estimated Revenue Range,Number of Exits,...,e_to_d_ratio,pe_to_e_ratio,total_funding_usd,last_funding_type,last_funding_amount,hub_tags,industry_multiples,company_valuation,months_since_founded,y
0,air up,Private,5.0,For Profit,"1,347",Active,"Commerce and Shopping, Food and Beverage, Other",251-500,$100M to $500M,NaN,...,0.0,0.0,67922929.0,Venture - Series Unknown,46744589.0,NaN,1.5,1.018844e+08,77,2
1,infinite roots,Private,1.0,For Profit,"1,875",Active,"Biotechnology, Food and Beverage, Health Care,...",51-100,NaN,NaN,...,0.0,0.0,86661948.0,Series B,57481860.0,NaN,3.0,2.599858e+08,77,2
2,instagrid,Private,2.0,For Profit,"1,950",Active,"Energy, Manufacturing",101-250,$1M to $10M,NaN,...,0.0,0.0,137401184.0,Series C,94927569.0,NaN,1.5,2.061018e+08,77,2
3,isar aerospace,Private,3.0,For Profit,"2,015",Active,"Information Technology, Science and Engineerin...",251-500,$10M to $50M,NaN,...,0.0,0.0,350641701.0,Series C,NaN,NaN,4.0,1.402567e+09,77,2
4,sosafe cyber security awareness,Private,3.0,For Profit,"2,054",Active,"Information Technology, Privacy and Security, ...",251-500,$50M to $100M,NaN,...,0.0,0.0,73000000.0,Series B,73000000.0,NaN,4.0,2.920000e+08,77,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2180,conias risk intelligence,Private,1.0,For Profit,"179,583",Active,"Information Technology, Professional Services,...",11-50,$1M to $10M,NaN,...,0.0,0.0,27284.0,Seed,27284.0,NaN,4.0,1.091360e+05,125,2
2181,corporate momentum,Private,1.0,For Profit,"182,871",Active,Professional Services,11-50,Less than $1M,NaN,...,0.0,0.0,81868.0,Grant,81868.0,NaN,3.5,2.865380e+05,125,2
2184,btc echo gmbh,Private,1.0,For Profit,"201,902",Active,"Blockchain and Cryptocurrency, Content and Pub...",11-50,$1M to $10M,NaN,...,0.0,0.0,145515.0,Seed,NaN,NaN,4.0,5.820600e+05,123,2
2185,swipy,Private,2.0,For Profit,"213,578",Closed,"Clothing and Apparel, Commerce and Shopping, C...",11-50,NaN,NaN,...,0.0,0.0,75000.0,Non-equity Assistance,NaN,NaN,1.5,1.125000e+05,116,2
2187,avant classic,Private,1.0,For Profit,"335,005",Closed,"Internet Services, Media and Entertainment",11-50,$1M to $10M,NaN,...,0.0,0.0,50000.0,Seed,50000.0,NaN,4.0,2.000000e+05,125,2

In [39]:
df[df["y"] == 1]

,Organization Name,IPO Status,Number of Founders,Company Type,CB Rank (Company),Operating Status,Industry Groups,Number of Employees,Estimated Revenue Range,Number of Exits,...,e_to_d_ratio,pe_to_e_ratio,total_funding_usd,last_funding_type,last_funding_amount,hub_tags,industry_multiples,company_valuation,months_since_founded,y
6,agile robots ag,Private,3.0,For Profit,"2,553",Active,"Artificial Intelligence (AI), Data and Analyti...",501-1000,$50M to $100M,NaN,...,0.0,0.0,270050589.0,Venture - Series Unknown,30000000.0,Unicorn,4.0,1.080202e+09,77,1
7,atai life sciences,Public,4.0,For Profit,"2,728",Active,"Biotechnology, Health Care, Science and Engine...",101-250,Less than $1M,2.0,...,0.0,0.0,522100000.0,Post-IPO Debt,175000000.0,Exited Unicorn,3.0,1.566300e+09,77,1
20,enapter,Public,3.0,For Profit,"6,297",Active,"Energy, Natural Resources, Software, Sustainab...",101-250,$10M to $50M,NaN,...,0.0,0.0,132246582.0,Post-IPO Debt,26671161.0,NaN,1.5,1.983699e+08,80,1
34,hy2gen,Private,NaN,For Profit,"10,967",Active,"Agriculture and Farming, Manufacturing",11-50,$1M to $10M,NaN,...,0.0,0.0,227276085.0,Private Equity,227276084.0,NaN,2.0,4.545522e+08,80,1
35,cluno,Private,3.0,For Profit,"11,653",Active,"Commerce and Shopping, Other, Transportation",51-100,$1M to $10M,NaN,...,0.0,0.0,190190966.0,Debt Financing,154190965.0,NaN,1.5,2.852864e+08,80,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2156,wishcard technologies group,Private,2.0,For Profit,"129,372",Active,"Commerce and Shopping, Financial Services, Int...",101-250,$10M to $50M,NaN,...,0.0,0.0,50856135.0,Secondary Market,50856134.0,NaN,1.5,7.628420e+07,125,1
2170,edition f gmbh,Private,2.0,For Profit,"149,494",Active,"Data and Analytics, Internet Services, Media a...",11-50,$1M to $10M,NaN,...,0.0,0.0,1441367.0,Non-equity Assistance,537004.0,NaN,4.0,5.765468e+06,124,1
2175,lofelt,Private,3.0,For Profit,"155,770",Active,"Consumer Electronics, Hardware",11-50,$1M to $10M,NaN,...,0.0,0.0,6745373.0,Series A,NaN,NaN,1.5,1.011806e+07,125,1
2182,playtestcloud,Private,2.0,For Profit,"187,226",Active,"Data and Analytics, Design, Gaming, Mobile, Pl...",11-50,Less than $1M,NaN,...,0.0,0.0,129685.0,Grant,129684.0,NaN,4.0,5.187400e+05,121,1
2188,appiris,Private,3.0,For Profit,"466,833",Active,"Advertising, Consumer Electronics, Hardware, I...",11-50,NaN,NaN,...,0.0,0.0,1371723.0,Venture - Series Unknown,1371723.0,NaN,3.5,4.801030e+06,125,1

In [40]:
df[df["y"] == 0]

,Organization Name,IPO Status,Number of Founders,Company Type,CB Rank (Company),Operating Status,Industry Groups,Number of Employees,Estimated Revenue Range,Number of Exits,...,e_to_d_ratio,pe_to_e_ratio,total_funding_usd,last_funding_type,last_funding_amount,hub_tags,industry_multiples,company_valuation,months_since_founded,y
166,matchbase,Private,2.0,For Profit,"86,454",Closed,"Apps, Mobile, Software, Sports",11-50,Less than $1M,NaN,...,0.0,0.0,1012483.0,Pre-Seed,543055.0,NaN,4.0,4049932.0,77,0
204,network insight,Private,1.0,For Profit,"187,351",Closed,"Artificial Intelligence (AI), Data and Analyti...",11-50,NaN,NaN,...,0.0,0.0,192000.0,Grant,27000.0,NaN,4.0,768000.0,77,0
205,sciencemap,Private,4.0,For Profit,"199,776",Closed,"Administrative Services, Artificial Intelligen...",11-50,NaN,NaN,...,0.0,0.0,215406.0,Grant,154730.0,NaN,3.5,753921.0,84,0
443,mylorry,Private,2.0,For Profit,"155,479",Closed,"Commerce and Shopping, Food and Beverage, Mobi...",1001-5000,NaN,NaN,...,0.0,0.0,6777697.0,Angel,5694229.0,NaN,1.5,10166545.5,132,0
467,netbump,Private,NaN,For Profit,"1,713,988",Closed,"Hardware, Internet Services, Science and Engin...",11-50,NaN,NaN,...,0.0,0.0,3900000.0,Seed,3900000.0,NaN,4.0,15600000.0,128,0
553,wonder,Private,3.0,For Profit,"36,128",Closed,"Information Technology, Internet Services, Med...",11-50,$10M to $50M,NaN,...,0.0,0.0,12200000.0,Seed,11000000.0,NaN,4.0,48800000.0,53,0
634,unown,Private,2.0,For Profit,"82,393",Closed,"Clothing and Apparel, Commerce and Shopping, D...",11-50,$1M to $10M,NaN,...,0.0,0.0,3166420.0,Seed,2102388.0,NaN,1.5,4749630.0,56,0
689,dilecy,Private,3.0,For Profit,"194,958",Closed,"Information Technology, Internet Services, Oth...",11-50,NaN,NaN,...,0.0,0.0,55092.0,Pre-Seed,55092.0,NaN,4.0,220368.0,54,0
921,daliado,Private,1.0,For Profit,"147,205",Closed,"Blockchain and Cryptocurrency, Financial Servi...",11-50,Less than $1M,NaN,...,0.0,0.0,100000.0,Pre-Seed,80000.0,NaN,4.0,400000.0,38,0
925,dive platform gmbh,Private,3.0,For Profit,"160,490",Closed,"Apps, Internet Services, Media and Entertainme...",11-50,$1M to $10M,NaN,...,0.0,0.0,807961.0,Pre-Seed,588928.0,NaN,4.0,3231844.0,39,0
1010,smartexposee,Private,3.0,For Profit,"863,653",Closed,"Mobile, Platforms, Real Estate, Software",11-50,$1M to $10M,NaN,...,0.0,0.0,250000.0,Angel,250000.0,NaN,4.0,1000000.0,158,0
1014,meetone,Private,3.0,For Profit,"1,134,586",Closed,"Internet Services, Media and Entertainment",11-50,Less than $1M,NaN,...,0.0,0.0,34474532.0,Corporate Round,34474532.0,NaN,4.0,137898128.0,161,0
1190,bio lutions,Private,3.0,For Profit,"50,244",Closed,"Administrative Services, Manufacturing, Scienc...",11-50,$1M to $10M,NaN,...,0.0,0.0,11209814.0,Series A,9273753.0,NaN,3.5,39234349.0,89,0
1257,mia & ben,Private,2.0,For Profit,"79,745",Closed,"Food and Beverage, Health Care",11-50,$1M to $10M,NaN,...,0.0,0.0,5387459.0,Series A,2802376.0,NaN,1.5,8081188.5,88,0
1321,wysker,Private,3.0,For Profit,"114,768",Closed,"Apps, Commerce and Shopping, Internet Services...",11-50,Less than $1M,NaN,...,0.0,0.0,1781225.0,Seed,1736565.0,NaN,4.0,7124900.0,96,0
1727,lernstift,Private,3.0,For Profit,"153,742",Closed,"Consumer Electronics, Education, Hardware, Sof...",11-50,NaN,NaN,...,0.0,0.0,1244693.0,Product Crowdfunding,659661.0,NaN,1.5,1867039.5,139,0
1730,panono,Private,3.0,For Profit,"181,646",Closed,"Consumer Electronics, Content and Publishing, ...",11-50,$1M to $10M,NaN,...,0.0,0.0,3473295.0,Venture - Series Unknown,NaN,NaN,1.5,5209942.5,149,0
2095,cashboard,Private,5.0,For Profit,"46,792",Closed,"Financial Services, Lending and Investments",11-50,$1M to $10M,NaN,...,0.0,0.0,5163389.0,Series A,3163389.0,NaN,3.5,18071861.5,125,0
2148,productive mobile,Private,3.0,For Profit,"121,921",Closed,"Privacy and Security, Software",11-50,NaN,NaN,...,0.0,0.0,4182824.0,Seed,4182823.0,NaN,4.0,16731296.0,125,0
2163,von floerke,Private,1.0,For Profit,"140,854",Closed,"Clothing and Apparel, Commerce and Shopping, C...",11-50,$1M to $10M,NaN,...,0.0,0.0,1703939.0,Equity Crowdfunding,1703939.0,NaN,1.5,2555908.5,114,0
2164,bonativo,Private,1.0,For Profit,"141,708",Closed,"Commerce and Shopping, Food and Beverage, Inte...",11-50,$1M to $10M,NaN,...,0.0,0.0,3644307.0,Series A,3644306.0,NaN,1.5,5466460.5,125,0
2183,ava,Private,2.0,For Profit,"188,048",Closed,"Data and Analytics, Government and Military, I...",11-50,$1M to $10M,NaN,...,0.0,0.0,5015405.0,Venture - Series Unknown,NaN,NaN,4.0,20061620.0,113,0
2186,regional markt,Private,2.0,For Profit,"224,877",Closed,"Agriculture and Farming, Commerce and Shopping...",11-50,$1M to $10M,NaN,...,0.0,0.0,183876.0,Convertible Note,72797.0,NaN,2.0,367752.0,125,0

In [41]:
failure_secondary = [x for x in failure_secondary if x not in both_ways]
failure_secondary = [x for x in failure_secondary if x not in success_target]
failure_secondary = [x for x in failure_secondary if x not in secondary_success]
failure_secondary = [x for x in failure_secondary if x not in failure_target]

In [42]:
secondary_success = [x for x in secondary_success if x not in both_ways]
secondary_success = [x for x in secondary_success if x not in failure_target]
secondary_success = [x for x in secondary_success if x not in failure_secondary]
secondary_success = [x for x in secondary_success if x not in success_target]

In [43]:
len(set(failure_secondary))

77

In [44]:
len(set(secondary_success))

323

In [45]:
df.loc[list(set(secondary_success)), ["y"]] = 1

In [46]:
df.loc[list(set(failure_secondary)), ["y"]] = 0

In [47]:
certain_list = list(df[df["y"] < 2].index)

In [48]:
undecided_list = [x for x in both_ways if x not in certain_list]

In [49]:
df[df["y"] < 2]

,Organization Name,IPO Status,Number of Founders,Company Type,CB Rank (Company),Operating Status,Industry Groups,Number of Employees,Estimated Revenue Range,Number of Exits,...,e_to_d_ratio,pe_to_e_ratio,total_funding_usd,last_funding_type,last_funding_amount,hub_tags,industry_multiples,company_valuation,months_since_founded,y
1,infinite roots,Private,1.0,For Profit,"1,875",Active,"Biotechnology, Food and Beverage, Health Care,...",51-100,NaN,NaN,...,0.0,0.0,86661948.0,Series B,57481860.0,NaN,3.0,2.599858e+08,77,1
2,instagrid,Private,2.0,For Profit,"1,950",Active,"Energy, Manufacturing",101-250,$1M to $10M,NaN,...,0.0,0.0,137401184.0,Series C,94927569.0,NaN,1.5,2.061018e+08,77,1
3,isar aerospace,Private,3.0,For Profit,"2,015",Active,"Information Technology, Science and Engineerin...",251-500,$10M to $50M,NaN,...,0.0,0.0,350641701.0,Series C,NaN,NaN,4.0,1.402567e+09,77,1
5,wandelbots,Private,8.0,For Profit,"2,128",Active,"Artificial Intelligence (AI), Consumer Electro...",101-250,$1M to $10M,NaN,...,0.0,0.0,122184409.0,Series C,84000000.0,NaN,4.0,4.887376e+08,80,1
6,agile robots ag,Private,3.0,For Profit,"2,553",Active,"Artificial Intelligence (AI), Data and Analyti...",501-1000,$50M to $100M,NaN,...,0.0,0.0,270050589.0,Venture - Series Unknown,30000000.0,Unicorn,4.0,1.080202e+09,77,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2175,lofelt,Private,3.0,For Profit,"155,770",Active,"Consumer Electronics, Hardware",11-50,$1M to $10M,NaN,...,0.0,0.0,6745373.0,Series A,NaN,NaN,1.5,1.011806e+07,125,1
2182,playtestcloud,Private,2.0,For Profit,"187,226",Active,"Data and Analytics, Design, Gaming, Mobile, Pl...",11-50,Less than $1M,NaN,...,0.0,0.0,129685.0,Grant,129684.0,NaN,4.0,5.187400e+05,121,1
2183,ava,Private,2.0,For Profit,"188,048",Closed,"Data and Analytics, Government and Military, I...",11-50,$1M to $10M,NaN,...,0.0,0.0,5015405.0,Venture - Series Unknown,NaN,NaN,4.0,2.006162e+07,113,0
2186,regional markt,Private,2.0,For Profit,"224,877",Closed,"Agriculture and Farming, Commerce and Shopping...",11-50,$1M to $10M,NaN,...,0.0,0.0,183876.0,Convertible Note,72797.0,NaN,2.0,3.677520e+05,125,0
2188,appiris,Private,3.0,For Profit,"466,833",Active,"Advertising, Consumer Electronics, Hardware, I...",11-50,NaN,NaN,...,0.0,0.0,1371723.0,Venture - Series Unknown,1371723.0,NaN,3.5,4.801030e+06,125,1

In [50]:
df.columns

Index(['Organization Name', 'IPO Status', 'Number of Founders', 'Company Type',
       'CB Rank (Company)', 'Operating Status', 'Industry Groups',
       'Number of Employees', 'Estimated Revenue Range', 'Number of Exits',
       'Number of Sub-Orgs', 'city', 'state', 'funding_status',
       'revenue_range', 'no_employees', 'lat', 'lon', 'no_founders',
       'industry', 'industry_groups', 'industry_groups_andreas', 'website',
       'phone', 'email', 'linkedin', 'twitter', 'facebook', 'articles',
       'founded_year', 'last_funding_year', 'exit_year', 'closed_year',
       'no_investors', 'no_fund_rounds', 'acquired', 'private_ipo',
       'company_type', 'operting_status', 'no_lead_investors', 'no_sub_orgs',
       'no_exits', 'has_preseed', 'has_seed', 'has_series_a', 'has_series_b',
       'has_series_c', 'has_series_d', 'has_series_e', 'has_angel',
       'has_debt_financing', 'has_grant', 'has_corporate_round',
       'has_series_x', 'has_ico', 'has_other_funding', 'preseed_fund',
       'seed_fund', 'series_a_fund', 'series_b_fund', 'series_c_fund',
       'series_d_fund', 'series_e_fund', 'private_equity_fund',
       'seed_to_pre_ratio', 'a_to_seed_ratio', 'b_to_a_ratio', 'c_to_b_ratio',
       'd_to_c_ratio', 'e_to_d_ratio', 'pe_to_e_ratio', 'total_funding_usd',
       'last_funding_type', 'last_funding_amount', 'hub_tags',
       'industry_multiples', 'company_valuation', 'months_since_founded', 'y'],
      dtype='object')

In [51]:
y = [
    "exit_year", "closed_year", "acquired", "funding_status", "has_series_d", "has_series_e"
]

Pre-Seed: $50,000 - $500,000
Seed: $500,000 - $2 Millionen
Series A: $2 Millionen - $15 Millionen
Series B: $15 Millionen - $50 Millionen
Series C: $50 Millionen - $100 Millionen
Series D: $100 Millionen - $200 Millionen
Series E und darüber hinaus: $200 Millionen und mehr

In [52]:
export_df = df.loc[:, ['state', 'funding_status', 'revenue_range', 'no_employees',
       'no_founders', 'industry_groups', 'website', 'phone', 'email',
       'linkedin', 'twitter', 'facebook', 'founded_year','no_investors', 'no_fund_rounds', 'private_ipo', 'company_type',
       'operting_status', 'no_lead_investors', 'no_sub_orgs',
       'has_preseed', 'has_seed', 'has_series_a', 'has_series_b',
       'has_series_c', 'has_series_d', 'has_series_e', 'has_angel',
       'has_debt_financing', 'has_grant', 'has_corporate_round',
       'has_series_x', 'has_ico', 'total_funding_usd', 'y']]

In [53]:
df.shape

(2184, 79)

In [54]:
df.to_csv("../raw_data/X_y_data2.csv")

In [55]:
shortlisted = df[df.y<2]

In [56]:
shortlisted.to_csv("../raw_data/X_y_data3.csv")